### ISSUE TITLE
Help in setting the environment up and go

### ISSUE THREAD

**Issue by Tempuser000** [node-app/Nodelike#51]
Hi,

So I wanted to check this project out, but since I am somewhat new I think I am having some issues. 

I initially built the libNodelike.a for different architectures I needed and added it to my project with reference to NLContext#attachToContext:(JSContext *) as mentioned in https://github.com/node-app/Nodelike/wiki/Incorporating-Nodelike-into-your-own-objective-C-project; however when I think it attempted to start "node" it blew up.

Then I read that I should try to use Pods for the build to hopefully make things work and got Pod's Build to work; however no artifacts were created making me wonder what is going on.

Ultimately my goal is to try this framework out to see if I can use 3rd party modules [i.e. passport and etc], but frankly I am lost as I can not find too many docs of where I need to include node_modules to as in traditional npm/node and etc.

Thanks for the help!

**Comment by BlackWolf** [comment]
It has been a while since I last used Nodelike, but a few notes on this:

1) I haven't used Pods as I found it to be quite annoying, so I can't say anything about that. I created a fork at https://github.com/BlackWolf/Nodelike/ that doesn't require Pods (download via `git clone --recursive URL`). Please note that the fork SHOULD work standalone, but was created for another project of mine. Just build it, add the .a to your project and make sure that the NodelikeResources.bundle is added to the "Copy files" build phase of your project.

2) That fork might help you out anyway, as it was designed to make Nodelike compatible with most (all?) non-native Node.js modules (so basically everything that comes as javascript). 

3) As for the node_modules path, I ended up adding my own at the end of lib/modules.js to `Module._initPaths`. If I remember correctly, Nodelike will search all folders at to the paths there and all parent folders of these folders

4) If you clarify what "blows up" means I might be able to help you out there ^^

**Comment by Tempuser000** [comment]
Hey BlackWolf.

First of all thanks for the response =D.  Ok so the "blows up" that I was mentioning was in the invocation of 

NLContext#attachToContext:(JSContext *)

and the result was 

EXC_BAD_ACCESS.

Anyway i guess this project is no longer maintained, making it probably not usable anymore.  Still thx for the response appreciate it much!!!
